
package jp.yahooapis.ss.v201808.pagefeeditem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PageFeedItemServiceService", targetNamespace = "http://ss.yahooapis.jp/V201808/PageFeedItem", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201808/PageFeedItemService?wsdl")
public class PageFeedItemServiceService
    extends Service
{

    private final static URL PAGEFEEDITEMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PAGEFEEDITEMSERVICESERVICE_EXCEPTION;
    private final static QName PAGEFEEDITEMSERVICESERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201808/PageFeedItem", "PageFeedItemServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201808/PageFeedItemService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAGEFEEDITEMSERVICESERVICE_WSDL_LOCATION = url;
        PAGEFEEDITEMSERVICESERVICE_EXCEPTION = e;
    }

    public PageFeedItemServiceService() {
        super(__getWsdlLocation(), PAGEFEEDITEMSERVICESERVICE_QNAME);
    }

    public PageFeedItemServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAGEFEEDITEMSERVICESERVICE_QNAME, features);
    }

    public PageFeedItemServiceService(URL wsdlLocation) {
        super(wsdlLocation, PAGEFEEDITEMSERVICESERVICE_QNAME);
    }

    public PageFeedItemServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAGEFEEDITEMSERVICESERVICE_QNAME, features);
    }

    public PageFeedItemServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PageFeedItemServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PageFeedItemServiceInterface
     */
    @WebEndpoint(name = "PageFeedItemService")
    public PageFeedItemServiceInterface getPageFeedItemService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201808/PageFeedItem", "PageFeedItemService"), PageFeedItemServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PageFeedItemServiceInterface
     */
    @WebEndpoint(name = "PageFeedItemService")
    public PageFeedItemServiceInterface getPageFeedItemService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201808/PageFeedItem", "PageFeedItemService"), PageFeedItemServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGEFEEDITEMSERVICESERVICE_EXCEPTION!= null) {
            throw PAGEFEEDITEMSERVICESERVICE_EXCEPTION;
        }
        return PAGEFEEDITEMSERVICESERVICE_WSDL_LOCATION;
    }

}
