
package jp.yahooapis.ss.v201901.campaignretargetinglist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CampaignRetargetingListService", targetNamespace = "http://ss.yahooapis.jp/V201901/CampaignRetargetingList", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201901/CampaignRetargetingListService?wsdl")
public class CampaignRetargetingListService
    extends Service
{

    private final static URL CAMPAIGNRETARGETINGLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION;
    private final static QName CAMPAIGNRETARGETINGLISTSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201901/CampaignRetargetingList", "CampaignRetargetingListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201901/CampaignRetargetingListService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAMPAIGNRETARGETINGLISTSERVICE_WSDL_LOCATION = url;
        CAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION = e;
    }

    public CampaignRetargetingListService() {
        super(__getWsdlLocation(), CAMPAIGNRETARGETINGLISTSERVICE_QNAME);
    }

    public CampaignRetargetingListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAMPAIGNRETARGETINGLISTSERVICE_QNAME, features);
    }

    public CampaignRetargetingListService(URL wsdlLocation) {
        super(wsdlLocation, CAMPAIGNRETARGETINGLISTSERVICE_QNAME);
    }

    public CampaignRetargetingListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAMPAIGNRETARGETINGLISTSERVICE_QNAME, features);
    }

    public CampaignRetargetingListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampaignRetargetingListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CampaignRetargetingListServiceInterface
     */
    @WebEndpoint(name = "CampaignRetargetingListService")
    public CampaignRetargetingListServiceInterface getCampaignRetargetingListService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/CampaignRetargetingList", "CampaignRetargetingListService"), CampaignRetargetingListServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CampaignRetargetingListServiceInterface
     */
    @WebEndpoint(name = "CampaignRetargetingListService")
    public CampaignRetargetingListServiceInterface getCampaignRetargetingListService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/CampaignRetargetingList", "CampaignRetargetingListService"), CampaignRetargetingListServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION!= null) {
            throw CAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION;
        }
        return CAMPAIGNRETARGETINGLISTSERVICE_WSDL_LOCATION;
    }

}
