
package jp.yahooapis.ss.v201901.retargetinglist;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201901.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RetargetingListServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList")
@XmlSeeAlso({
    jp.yahooapis.ss.v201901.ObjectFactory.class,
    jp.yahooapis.ss.v201901.retargetinglist.ObjectFactory.class
})
public interface RetargetingListServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", className = "jp.yahooapis.ss.v201901.retargetinglist.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", className = "jp.yahooapis.ss.v201901.retargetinglist.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList")
        RetargetingListSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", mode = WebParam.Mode.OUT)
        Holder<RetargetingListPage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", className = "jp.yahooapis.ss.v201901.retargetinglist.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", className = "jp.yahooapis.ss.v201901.retargetinglist.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList")
        RetargetingListOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", mode = WebParam.Mode.OUT)
        Holder<RetargetingListReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "getCustomKey", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", className = "jp.yahooapis.ss.v201901.retargetinglist.GetCustomKey")
    @ResponseWrapper(localName = "getCustomKeyResponse", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", className = "jp.yahooapis.ss.v201901.retargetinglist.GetCustomKeyResponse")
    public void getCustomKey(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList")
        GetCustomKeySelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", mode = WebParam.Mode.OUT)
        Holder<RetargetingListCustomKeyPage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201901/RetargetingList", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
