
package jp.yahooapis.ss.v201909.campaignlabel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CampaignLabelService", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignLabel", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201909/CampaignLabelService?wsdl")
public class CampaignLabelService
    extends Service
{

    private final static URL CAMPAIGNLABELSERVICE_WSDL_LOCATION;
    private final static WebServiceException CAMPAIGNLABELSERVICE_EXCEPTION;
    private final static QName CAMPAIGNLABELSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201909/CampaignLabel", "CampaignLabelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201909/CampaignLabelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAMPAIGNLABELSERVICE_WSDL_LOCATION = url;
        CAMPAIGNLABELSERVICE_EXCEPTION = e;
    }

    public CampaignLabelService() {
        super(__getWsdlLocation(), CAMPAIGNLABELSERVICE_QNAME);
    }

    public CampaignLabelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAMPAIGNLABELSERVICE_QNAME, features);
    }

    public CampaignLabelService(URL wsdlLocation) {
        super(wsdlLocation, CAMPAIGNLABELSERVICE_QNAME);
    }

    public CampaignLabelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAMPAIGNLABELSERVICE_QNAME, features);
    }

    public CampaignLabelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampaignLabelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CampaignLabelServiceInterface
     */
    @WebEndpoint(name = "CampaignLabelService")
    public CampaignLabelServiceInterface getCampaignLabelService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201909/CampaignLabel", "CampaignLabelService"), CampaignLabelServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CampaignLabelServiceInterface
     */
    @WebEndpoint(name = "CampaignLabelService")
    public CampaignLabelServiceInterface getCampaignLabelService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201909/CampaignLabel", "CampaignLabelService"), CampaignLabelServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAMPAIGNLABELSERVICE_EXCEPTION!= null) {
            throw CAMPAIGNLABELSERVICE_EXCEPTION;
        }
        return CAMPAIGNLABELSERVICE_WSDL_LOCATION;
    }

}
