
package jp.yahooapis.ss.V5.TrafficEstimatorService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrafficEstimatorService", targetNamespace = "http://ss.yahooapis.jp/V5", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V5.3/TrafficEstimatorService?wsdl")
public class TrafficEstimatorService
    extends Service
{

    private final static URL TRAFFICESTIMATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAFFICESTIMATORSERVICE_EXCEPTION;
    private final static QName TRAFFICESTIMATORSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V5", "TrafficEstimatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V5.3/TrafficEstimatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAFFICESTIMATORSERVICE_WSDL_LOCATION = url;
        TRAFFICESTIMATORSERVICE_EXCEPTION = e;
    }

    public TrafficEstimatorService() {
        super(__getWsdlLocation(), TRAFFICESTIMATORSERVICE_QNAME);
    }

    public TrafficEstimatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAFFICESTIMATORSERVICE_QNAME, features);
    }

    public TrafficEstimatorService(URL wsdlLocation) {
        super(wsdlLocation, TRAFFICESTIMATORSERVICE_QNAME);
    }

    public TrafficEstimatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAFFICESTIMATORSERVICE_QNAME, features);
    }

    public TrafficEstimatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrafficEstimatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrafficEstimatorServiceInterface
     */
    @WebEndpoint(name = "TrafficEstimatorService")
    public TrafficEstimatorServiceInterface getTrafficEstimatorService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V5", "TrafficEstimatorService"), TrafficEstimatorServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrafficEstimatorServiceInterface
     */
    @WebEndpoint(name = "TrafficEstimatorService")
    public TrafficEstimatorServiceInterface getTrafficEstimatorService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V5", "TrafficEstimatorService"), TrafficEstimatorServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAFFICESTIMATORSERVICE_EXCEPTION!= null) {
            throw TRAFFICESTIMATORSERVICE_EXCEPTION;
        }
        return TRAFFICESTIMATORSERVICE_WSDL_LOCATION;
    }

}
