
package jp.yahooapis.ss.v201901.bidlandscape;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201901.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BidLandscapeServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201901/BidLandscape")
@XmlSeeAlso({
    jp.yahooapis.ss.v201901.ObjectFactory.class,
    jp.yahooapis.ss.v201901.bidlandscape.ObjectFactory.class
})
public interface BidLandscapeServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://ss.yahooapis.jp/V201901/BidLandscape", className = "jp.yahooapis.ss.v201901.bidlandscape.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ss.yahooapis.jp/V201901/BidLandscape", className = "jp.yahooapis.ss.v201901.bidlandscape.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201901/BidLandscape")
        BidLandscapeSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201901/BidLandscape", mode = WebParam.Mode.OUT)
        Holder<BidLandscapePage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201901/BidLandscape", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
