
package jp.yahooapis.ss.v201909.adgroupcriterionlabel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201909.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdGroupCriterionLabelServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupCriterionLabel")
@XmlSeeAlso({
    jp.yahooapis.ss.v201909.ObjectFactory.class,
    jp.yahooapis.ss.v201909.adgroupcriterionlabel.ObjectFactory.class
})
public interface AdGroupCriterionLabelServiceInterface {


    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupCriterionLabel", className = "jp.yahooapis.ss.v201909.adgroupcriterionlabel.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupCriterionLabel", className = "jp.yahooapis.ss.v201909.adgroupcriterionlabel.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupCriterionLabel")
        AdGroupCriterionLabelOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupCriterionLabel", mode = WebParam.Mode.OUT)
        Holder<AdGroupCriterionLabelReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupCriterionLabel", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
