
package jp.yahooapis.ss.V6.FeedFolderService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeedFolderService", targetNamespace = "http://ss.yahooapis.jp/V6", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V6.0/FeedFolderService?wsdl")
public class FeedFolderService
    extends Service
{

    private final static URL FEEDFOLDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FEEDFOLDERSERVICE_EXCEPTION;
    private final static QName FEEDFOLDERSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V6", "FeedFolderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V6.0/FeedFolderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEEDFOLDERSERVICE_WSDL_LOCATION = url;
        FEEDFOLDERSERVICE_EXCEPTION = e;
    }

    public FeedFolderService() {
        super(__getWsdlLocation(), FEEDFOLDERSERVICE_QNAME);
    }

    public FeedFolderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEEDFOLDERSERVICE_QNAME, features);
    }

    public FeedFolderService(URL wsdlLocation) {
        super(wsdlLocation, FEEDFOLDERSERVICE_QNAME);
    }

    public FeedFolderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEEDFOLDERSERVICE_QNAME, features);
    }

    public FeedFolderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeedFolderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeedFolderServiceInterface
     */
    @WebEndpoint(name = "FeedFolderService")
    public FeedFolderServiceInterface getFeedFolderService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "FeedFolderService"), FeedFolderServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeedFolderServiceInterface
     */
    @WebEndpoint(name = "FeedFolderService")
    public FeedFolderServiceInterface getFeedFolderService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "FeedFolderService"), FeedFolderServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEEDFOLDERSERVICE_EXCEPTION!= null) {
            throw FEEDFOLDERSERVICE_EXCEPTION;
        }
        return FEEDFOLDERSERVICE_WSDL_LOCATION;
    }

}
