
package jp.yahooapis.ss.V6.NegativeCampaignRetargetingListService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NegativeCampaignRetargetingListService", targetNamespace = "http://ss.yahooapis.jp/V6", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V6.1/NegativeCampaignRetargetingListService?wsdl")
public class NegativeCampaignRetargetingListService
    extends Service
{

    private final static URL NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION;
    private final static QName NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V6", "NegativeCampaignRetargetingListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V6.1/NegativeCampaignRetargetingListService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_WSDL_LOCATION = url;
        NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION = e;
    }

    public NegativeCampaignRetargetingListService() {
        super(__getWsdlLocation(), NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_QNAME);
    }

    public NegativeCampaignRetargetingListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_QNAME, features);
    }

    public NegativeCampaignRetargetingListService(URL wsdlLocation) {
        super(wsdlLocation, NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_QNAME);
    }

    public NegativeCampaignRetargetingListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_QNAME, features);
    }

    public NegativeCampaignRetargetingListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NegativeCampaignRetargetingListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NegativeCampaignRetargetingListServiceInterface
     */
    @WebEndpoint(name = "NegativeCampaignRetargetingListService")
    public NegativeCampaignRetargetingListServiceInterface getNegativeCampaignRetargetingListService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "NegativeCampaignRetargetingListService"), NegativeCampaignRetargetingListServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NegativeCampaignRetargetingListServiceInterface
     */
    @WebEndpoint(name = "NegativeCampaignRetargetingListService")
    public NegativeCampaignRetargetingListServiceInterface getNegativeCampaignRetargetingListService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "NegativeCampaignRetargetingListService"), NegativeCampaignRetargetingListServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION!= null) {
            throw NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_EXCEPTION;
        }
        return NEGATIVECAMPAIGNRETARGETINGLISTSERVICE_WSDL_LOCATION;
    }

}
