
package jp.yahooapis.ss.v201808.adgroupretargetinglist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdGroupRetargetingListService", targetNamespace = "http://ss.yahooapis.jp/V201808/AdGroupRetargetingList", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201808/AdGroupRetargetingListService?wsdl")
public class AdGroupRetargetingListService
    extends Service
{

    private final static URL ADGROUPRETARGETINGLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADGROUPRETARGETINGLISTSERVICE_EXCEPTION;
    private final static QName ADGROUPRETARGETINGLISTSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201808/AdGroupRetargetingList", "AdGroupRetargetingListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201808/AdGroupRetargetingListService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADGROUPRETARGETINGLISTSERVICE_WSDL_LOCATION = url;
        ADGROUPRETARGETINGLISTSERVICE_EXCEPTION = e;
    }

    public AdGroupRetargetingListService() {
        super(__getWsdlLocation(), ADGROUPRETARGETINGLISTSERVICE_QNAME);
    }

    public AdGroupRetargetingListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADGROUPRETARGETINGLISTSERVICE_QNAME, features);
    }

    public AdGroupRetargetingListService(URL wsdlLocation) {
        super(wsdlLocation, ADGROUPRETARGETINGLISTSERVICE_QNAME);
    }

    public AdGroupRetargetingListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADGROUPRETARGETINGLISTSERVICE_QNAME, features);
    }

    public AdGroupRetargetingListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupRetargetingListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdGroupRetargetingListServiceInterface
     */
    @WebEndpoint(name = "AdGroupRetargetingListService")
    public AdGroupRetargetingListServiceInterface getAdGroupRetargetingListService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201808/AdGroupRetargetingList", "AdGroupRetargetingListService"), AdGroupRetargetingListServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupRetargetingListServiceInterface
     */
    @WebEndpoint(name = "AdGroupRetargetingListService")
    public AdGroupRetargetingListServiceInterface getAdGroupRetargetingListService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201808/AdGroupRetargetingList", "AdGroupRetargetingListService"), AdGroupRetargetingListServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADGROUPRETARGETINGLISTSERVICE_EXCEPTION!= null) {
            throw ADGROUPRETARGETINGLISTSERVICE_EXCEPTION;
        }
        return ADGROUPRETARGETINGLISTSERVICE_WSDL_LOCATION;
    }

}
