
package jp.yahooapis.ss.v201909.campaigncriterion;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201909.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CampaignCriterionServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion")
@XmlSeeAlso({
    jp.yahooapis.ss.v201909.ObjectFactory.class,
    jp.yahooapis.ss.v201909.campaigncriterion.ObjectFactory.class
})
public interface CampaignCriterionServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", className = "jp.yahooapis.ss.v201909.campaigncriterion.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", className = "jp.yahooapis.ss.v201909.campaigncriterion.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion")
        CampaignCriterionSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", mode = WebParam.Mode.OUT)
        Holder<CampaignCriterionPage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", className = "jp.yahooapis.ss.v201909.campaigncriterion.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", className = "jp.yahooapis.ss.v201909.campaigncriterion.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion")
        CampaignCriterionOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", mode = WebParam.Mode.OUT)
        Holder<CampaignCriterionReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201909/CampaignCriterion", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
