
package jp.yahooapis.ss.v201805.accounttrackingurl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201805.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountTrackingUrlServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl")
@XmlSeeAlso({
    jp.yahooapis.ss.v201805.ObjectFactory.class,
    jp.yahooapis.ss.v201805.accounttrackingurl.ObjectFactory.class
})
public interface AccountTrackingUrlServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", className = "jp.yahooapis.ss.v201805.accounttrackingurl.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", className = "jp.yahooapis.ss.v201805.accounttrackingurl.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl")
        AccountTrackingUrlSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", mode = WebParam.Mode.OUT)
        Holder<AccountTrackingUrlPage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", className = "jp.yahooapis.ss.v201805.accounttrackingurl.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", className = "jp.yahooapis.ss.v201805.accounttrackingurl.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl")
        AccountTrackingUrlOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", mode = WebParam.Mode.OUT)
        Holder<AccountTrackingUrlReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201805/AccountTrackingUrl", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
