
package jp.yahooapis.ss.V6.BalanceService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BalanceService", targetNamespace = "http://ss.yahooapis.jp/V6", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V6.3/BalanceService?wsdl")
public class BalanceService
    extends Service
{

    private final static URL BALANCESERVICE_WSDL_LOCATION;
    private final static WebServiceException BALANCESERVICE_EXCEPTION;
    private final static QName BALANCESERVICE_QNAME = new QName("http://ss.yahooapis.jp/V6", "BalanceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V6.3/BalanceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BALANCESERVICE_WSDL_LOCATION = url;
        BALANCESERVICE_EXCEPTION = e;
    }

    public BalanceService() {
        super(__getWsdlLocation(), BALANCESERVICE_QNAME);
    }

    public BalanceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BALANCESERVICE_QNAME, features);
    }

    public BalanceService(URL wsdlLocation) {
        super(wsdlLocation, BALANCESERVICE_QNAME);
    }

    public BalanceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BALANCESERVICE_QNAME, features);
    }

    public BalanceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BalanceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BalanceServiceInterface
     */
    @WebEndpoint(name = "BalanceService")
    public BalanceServiceInterface getBalanceService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "BalanceService"), BalanceServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BalanceServiceInterface
     */
    @WebEndpoint(name = "BalanceService")
    public BalanceServiceInterface getBalanceService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "BalanceService"), BalanceServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BALANCESERVICE_EXCEPTION!= null) {
            throw BALANCESERVICE_EXCEPTION;
        }
        return BALANCESERVICE_WSDL_LOCATION;
    }

}
