
package jp.yahooapis.ss.v201901.adgroupadlabel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdGroupAdLabelService", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupAdLabel", wsdlLocation = "https://ss.yahooapis.jp/services/V201901/AdGroupAdLabelService?wsdl")
public class AdGroupAdLabelService
    extends Service
{

    private final static URL ADGROUPADLABELSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADGROUPADLABELSERVICE_EXCEPTION;
    private final static QName ADGROUPADLABELSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201901/AdGroupAdLabel", "AdGroupAdLabelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ss.yahooapis.jp/services/V201901/AdGroupAdLabelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADGROUPADLABELSERVICE_WSDL_LOCATION = url;
        ADGROUPADLABELSERVICE_EXCEPTION = e;
    }

    public AdGroupAdLabelService() {
        super(__getWsdlLocation(), ADGROUPADLABELSERVICE_QNAME);
    }

    public AdGroupAdLabelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADGROUPADLABELSERVICE_QNAME, features);
    }

    public AdGroupAdLabelService(URL wsdlLocation) {
        super(wsdlLocation, ADGROUPADLABELSERVICE_QNAME);
    }

    public AdGroupAdLabelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADGROUPADLABELSERVICE_QNAME, features);
    }

    public AdGroupAdLabelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupAdLabelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdGroupAdLabelServiceInterface
     */
    @WebEndpoint(name = "AdGroupAdLabelService")
    public AdGroupAdLabelServiceInterface getAdGroupAdLabelService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/AdGroupAdLabel", "AdGroupAdLabelService"), AdGroupAdLabelServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupAdLabelServiceInterface
     */
    @WebEndpoint(name = "AdGroupAdLabelService")
    public AdGroupAdLabelServiceInterface getAdGroupAdLabelService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/AdGroupAdLabel", "AdGroupAdLabelService"), AdGroupAdLabelServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADGROUPADLABELSERVICE_EXCEPTION!= null) {
            throw ADGROUPADLABELSERVICE_EXCEPTION;
        }
        return ADGROUPADLABELSERVICE_WSDL_LOCATION;
    }

}
