
package jp.yahooapis.ss.v201909.adgroupwebpage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdGroupWebpageService", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupWebpage", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201909/AdGroupWebpageService?wsdl")
public class AdGroupWebpageService
    extends Service
{

    private final static URL ADGROUPWEBPAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADGROUPWEBPAGESERVICE_EXCEPTION;
    private final static QName ADGROUPWEBPAGESERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201909/AdGroupWebpage", "AdGroupWebpageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201909/AdGroupWebpageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADGROUPWEBPAGESERVICE_WSDL_LOCATION = url;
        ADGROUPWEBPAGESERVICE_EXCEPTION = e;
    }

    public AdGroupWebpageService() {
        super(__getWsdlLocation(), ADGROUPWEBPAGESERVICE_QNAME);
    }

    public AdGroupWebpageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADGROUPWEBPAGESERVICE_QNAME, features);
    }

    public AdGroupWebpageService(URL wsdlLocation) {
        super(wsdlLocation, ADGROUPWEBPAGESERVICE_QNAME);
    }

    public AdGroupWebpageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADGROUPWEBPAGESERVICE_QNAME, features);
    }

    public AdGroupWebpageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupWebpageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdGroupWebpageServiceInterface
     */
    @WebEndpoint(name = "AdGroupWebpageService")
    public AdGroupWebpageServiceInterface getAdGroupWebpageService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201909/AdGroupWebpage", "AdGroupWebpageService"), AdGroupWebpageServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupWebpageServiceInterface
     */
    @WebEndpoint(name = "AdGroupWebpageService")
    public AdGroupWebpageServiceInterface getAdGroupWebpageService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201909/AdGroupWebpage", "AdGroupWebpageService"), AdGroupWebpageServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADGROUPWEBPAGESERVICE_EXCEPTION!= null) {
            throw ADGROUPWEBPAGESERVICE_EXCEPTION;
        }
        return ADGROUPWEBPAGESERVICE_WSDL_LOCATION;
    }

}
