
package jp.yahooapis.ss.v201909.adgrouplabel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdGroupLabelService", targetNamespace = "http://ss.yahooapis.jp/V201909/AdGroupLabel", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201909/AdGroupLabelService?wsdl")
public class AdGroupLabelService
    extends Service
{

    private final static URL ADGROUPLABELSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADGROUPLABELSERVICE_EXCEPTION;
    private final static QName ADGROUPLABELSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201909/AdGroupLabel", "AdGroupLabelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201909/AdGroupLabelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADGROUPLABELSERVICE_WSDL_LOCATION = url;
        ADGROUPLABELSERVICE_EXCEPTION = e;
    }

    public AdGroupLabelService() {
        super(__getWsdlLocation(), ADGROUPLABELSERVICE_QNAME);
    }

    public AdGroupLabelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADGROUPLABELSERVICE_QNAME, features);
    }

    public AdGroupLabelService(URL wsdlLocation) {
        super(wsdlLocation, ADGROUPLABELSERVICE_QNAME);
    }

    public AdGroupLabelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADGROUPLABELSERVICE_QNAME, features);
    }

    public AdGroupLabelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdGroupLabelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdGroupLabelServiceInterface
     */
    @WebEndpoint(name = "AdGroupLabelService")
    public AdGroupLabelServiceInterface getAdGroupLabelService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201909/AdGroupLabel", "AdGroupLabelService"), AdGroupLabelServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdGroupLabelServiceInterface
     */
    @WebEndpoint(name = "AdGroupLabelService")
    public AdGroupLabelServiceInterface getAdGroupLabelService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201909/AdGroupLabel", "AdGroupLabelService"), AdGroupLabelServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADGROUPLABELSERVICE_EXCEPTION!= null) {
            throw ADGROUPLABELSERVICE_EXCEPTION;
        }
        return ADGROUPLABELSERVICE_WSDL_LOCATION;
    }

}
