
package jp.yahooapis.ss.v201901.auditlog;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuditLogService", targetNamespace = "http://ss.yahooapis.jp/V201901/AuditLog", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V201901/AuditLogService?wsdl")
public class AuditLogService
    extends Service
{

    private final static URL AUDITLOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUDITLOGSERVICE_EXCEPTION;
    private final static QName AUDITLOGSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201901/AuditLog", "AuditLogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V201901/AuditLogService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUDITLOGSERVICE_WSDL_LOCATION = url;
        AUDITLOGSERVICE_EXCEPTION = e;
    }

    public AuditLogService() {
        super(__getWsdlLocation(), AUDITLOGSERVICE_QNAME);
    }

    public AuditLogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUDITLOGSERVICE_QNAME, features);
    }

    public AuditLogService(URL wsdlLocation) {
        super(wsdlLocation, AUDITLOGSERVICE_QNAME);
    }

    public AuditLogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUDITLOGSERVICE_QNAME, features);
    }

    public AuditLogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuditLogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuditLogServiceInterface
     */
    @WebEndpoint(name = "AuditLogService")
    public AuditLogServiceInterface getAuditLogService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/AuditLog", "AuditLogService"), AuditLogServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuditLogServiceInterface
     */
    @WebEndpoint(name = "AuditLogService")
    public AuditLogServiceInterface getAuditLogService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/AuditLog", "AuditLogService"), AuditLogServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUDITLOGSERVICE_EXCEPTION!= null) {
            throw AUDITLOGSERVICE_EXCEPTION;
        }
        return AUDITLOGSERVICE_WSDL_LOCATION;
    }

}
