
package jp.yahooapis.ss.v201808.keywordestimator;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201808.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KeywordEstimatorServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201808/KeywordEstimator")
@XmlSeeAlso({
    jp.yahooapis.ss.v201808.ObjectFactory.class,
    jp.yahooapis.ss.v201808.keywordestimator.ObjectFactory.class
})
public interface KeywordEstimatorServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://ss.yahooapis.jp/V201808/KeywordEstimator", className = "jp.yahooapis.ss.v201808.keywordestimator.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ss.yahooapis.jp/V201808/KeywordEstimator", className = "jp.yahooapis.ss.v201808.keywordestimator.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201808/KeywordEstimator")
        KeywordEstimatorSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201808/KeywordEstimator", mode = WebParam.Mode.OUT)
        Holder<KeywordEstimatorPage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201808/KeywordEstimator", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
