
package jp.yahooapis.ss.V6.RetargetingListService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RetargetingListService", targetNamespace = "http://ss.yahooapis.jp/V6", wsdlLocation = "https://sandbox.ss.yahooapis.jp/services/V6.1/RetargetingListService?wsdl")
public class RetargetingListService
    extends Service
{

    private final static URL RETARGETINGLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException RETARGETINGLISTSERVICE_EXCEPTION;
    private final static QName RETARGETINGLISTSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V6", "RetargetingListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.ss.yahooapis.jp/services/V6.1/RetargetingListService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RETARGETINGLISTSERVICE_WSDL_LOCATION = url;
        RETARGETINGLISTSERVICE_EXCEPTION = e;
    }

    public RetargetingListService() {
        super(__getWsdlLocation(), RETARGETINGLISTSERVICE_QNAME);
    }

    public RetargetingListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RETARGETINGLISTSERVICE_QNAME, features);
    }

    public RetargetingListService(URL wsdlLocation) {
        super(wsdlLocation, RETARGETINGLISTSERVICE_QNAME);
    }

    public RetargetingListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RETARGETINGLISTSERVICE_QNAME, features);
    }

    public RetargetingListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetargetingListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RetargetingListServiceInterface
     */
    @WebEndpoint(name = "RetargetingListService")
    public RetargetingListServiceInterface getRetargetingListService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "RetargetingListService"), RetargetingListServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetargetingListServiceInterface
     */
    @WebEndpoint(name = "RetargetingListService")
    public RetargetingListServiceInterface getRetargetingListService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V6", "RetargetingListService"), RetargetingListServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RETARGETINGLISTSERVICE_EXCEPTION!= null) {
            throw RETARGETINGLISTSERVICE_EXCEPTION;
        }
        return RETARGETINGLISTSERVICE_WSDL_LOCATION;
    }

}
