
package jp.yahooapis.ss.v201901.campaignwebpage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CampaignWebpageService", targetNamespace = "http://ss.yahooapis.jp/V201901/CampaignWebpage", wsdlLocation = "https://ss.yahooapis.jp/services/V201901/CampaignWebpageService?wsdl")
public class CampaignWebpageService
    extends Service
{

    private final static URL CAMPAIGNWEBPAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException CAMPAIGNWEBPAGESERVICE_EXCEPTION;
    private final static QName CAMPAIGNWEBPAGESERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201901/CampaignWebpage", "CampaignWebpageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ss.yahooapis.jp/services/V201901/CampaignWebpageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAMPAIGNWEBPAGESERVICE_WSDL_LOCATION = url;
        CAMPAIGNWEBPAGESERVICE_EXCEPTION = e;
    }

    public CampaignWebpageService() {
        super(__getWsdlLocation(), CAMPAIGNWEBPAGESERVICE_QNAME);
    }

    public CampaignWebpageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAMPAIGNWEBPAGESERVICE_QNAME, features);
    }

    public CampaignWebpageService(URL wsdlLocation) {
        super(wsdlLocation, CAMPAIGNWEBPAGESERVICE_QNAME);
    }

    public CampaignWebpageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAMPAIGNWEBPAGESERVICE_QNAME, features);
    }

    public CampaignWebpageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampaignWebpageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CampaignWebpageServiceInterface
     */
    @WebEndpoint(name = "CampaignWebpageService")
    public CampaignWebpageServiceInterface getCampaignWebpageService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/CampaignWebpage", "CampaignWebpageService"), CampaignWebpageServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CampaignWebpageServiceInterface
     */
    @WebEndpoint(name = "CampaignWebpageService")
    public CampaignWebpageServiceInterface getCampaignWebpageService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/CampaignWebpage", "CampaignWebpageService"), CampaignWebpageServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAMPAIGNWEBPAGESERVICE_EXCEPTION!= null) {
            throw CAMPAIGNWEBPAGESERVICE_EXCEPTION;
        }
        return CAMPAIGNWEBPAGESERVICE_WSDL_LOCATION;
    }

}
