
package jp.yahooapis.ss.v201901.adgroupwebpage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import jp.yahooapis.ss.v201901.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdGroupWebpageServiceInterface", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage")
@XmlSeeAlso({
    jp.yahooapis.ss.v201901.ObjectFactory.class,
    jp.yahooapis.ss.v201901.adgroupwebpage.ObjectFactory.class
})
public interface AdGroupWebpageServiceInterface {


    /**
     * 
     * @param selector
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", className = "jp.yahooapis.ss.v201901.adgroupwebpage.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", className = "jp.yahooapis.ss.v201901.adgroupwebpage.GetResponse")
    public void get(
        @WebParam(name = "selector", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage")
        AdGroupWebpageSelector selector,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", mode = WebParam.Mode.OUT)
        Holder<AdGroupWebpagePage> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

    /**
     * 
     * @param operations
     * @param rval
     * @param error
     * @throws ApiException
     */
    @WebMethod
    @RequestWrapper(localName = "mutate", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", className = "jp.yahooapis.ss.v201901.adgroupwebpage.Mutate")
    @ResponseWrapper(localName = "mutateResponse", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", className = "jp.yahooapis.ss.v201901.adgroupwebpage.MutateResponse")
    public void mutate(
        @WebParam(name = "operations", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage")
        AdGroupWebpageOperation operations,
        @WebParam(name = "rval", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", mode = WebParam.Mode.OUT)
        Holder<AdGroupWebpageReturnValue> rval,
        @WebParam(name = "error", targetNamespace = "http://ss.yahooapis.jp/V201901/AdGroupWebpage", mode = WebParam.Mode.OUT)
        Holder<List<Error>> error)
        throws ApiException
    ;

}
