
package jp.yahooapis.ss.v201901.pagefeeditem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PageFeedItemService", targetNamespace = "http://ss.yahooapis.jp/V201901/PageFeedItem", wsdlLocation = "https://ss.yahooapis.jp/services/V201901/PageFeedItemService?wsdl")
public class PageFeedItemService
    extends Service
{

    private final static URL PAGEFEEDITEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAGEFEEDITEMSERVICE_EXCEPTION;
    private final static QName PAGEFEEDITEMSERVICE_QNAME = new QName("http://ss.yahooapis.jp/V201901/PageFeedItem", "PageFeedItemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ss.yahooapis.jp/services/V201901/PageFeedItemService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAGEFEEDITEMSERVICE_WSDL_LOCATION = url;
        PAGEFEEDITEMSERVICE_EXCEPTION = e;
    }

    public PageFeedItemService() {
        super(__getWsdlLocation(), PAGEFEEDITEMSERVICE_QNAME);
    }

    public PageFeedItemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAGEFEEDITEMSERVICE_QNAME, features);
    }

    public PageFeedItemService(URL wsdlLocation) {
        super(wsdlLocation, PAGEFEEDITEMSERVICE_QNAME);
    }

    public PageFeedItemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAGEFEEDITEMSERVICE_QNAME, features);
    }

    public PageFeedItemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PageFeedItemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PageFeedItemServiceInterface
     */
    @WebEndpoint(name = "PageFeedItemService")
    public PageFeedItemServiceInterface getPageFeedItemService() {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/PageFeedItem", "PageFeedItemService"), PageFeedItemServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PageFeedItemServiceInterface
     */
    @WebEndpoint(name = "PageFeedItemService")
    public PageFeedItemServiceInterface getPageFeedItemService(WebServiceFeature... features) {
        return super.getPort(new QName("http://ss.yahooapis.jp/V201901/PageFeedItem", "PageFeedItemService"), PageFeedItemServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGEFEEDITEMSERVICE_EXCEPTION!= null) {
            throw PAGEFEEDITEMSERVICE_EXCEPTION;
        }
        return PAGEFEEDITEMSERVICE_WSDL_LOCATION;
    }

}
